name: Automatic build

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxss1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 qt5-default libqt5gui5 libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5printsupport5 libqt5quickwidgets5 qml-module-qtquick-controls libqt5x11extras5 binutils cmake pkg-config qtbase5-dev qtwebengine5-dev libqt5x11extras5-dev  qtbase5-private-dev libssl-dev libxss-dev libxmu-dev
    - name: Configure
      run: qmake .
    - name: Build
      run: make -j2

  macOS:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        brew install qt
        echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
        brew install xz
        brew install git
    - name: Configure
      run: |
        export PATH="/usr/local/opt/qt/bin:/usr/local/opt/git/bin:$PATH"
        ls /usr/local/opt/qt/bin
        qmake .
    - name: Build
      run: make -j2

  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        choco install wget
        choco install 7z
    - name: Install Qt
      run: |
        wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
        python qli-installer.py 5.12.3 windows desktop win32_mingw73

